
import { DashboardCardData } from './types';
import {
  XIcon,
  LinkIcon,
  PencilIcon,
  CalendarIcon,
  ChatBubbleIcon,
  BookOpenIcon,
  UsersIcon,
  TrophyIcon,
  ClipboardListIcon,
  UserAddIcon,
} from './components/icons';

export const DASHBOARD_CARDS: DashboardCardData[] = [
  {
    id: 'x-share',
    title: 'Xで宣伝してね',
    description: 'クリックでXの投稿画面を開き、もくよう会を宣伝。投稿後にURLを登録してください。',
    icon: XIcon,
    metric: 'xShareCount',
    actionType: 'X_SHARE',
    actionText: 'Xで投稿する',
  },
  {
    id: 'finx-profile',
    title: 'Finxプロフィール更新',
    description: 'Finxのプロフィールページへ移動します。編集が完了したらボタンで自己申告してください。',
    icon: LinkIcon,
    metric: 'finxProfileEditCount',
    actionType: 'EXTERNAL_LINK',
    actionText: '編集完了を申告',
    externalLink: 'https://finx.example.com/profile',
  },
  {
    id: 'finx-intro',
    title: 'Finx自己紹介部屋に投稿',
    description: 'Finxの「自己紹介部屋」へ移動します。投稿が完了したらボタンで自己申告してください。',
    icon: PencilIcon,
    metric: 'finxIntroPostCount',
    actionType: 'EXTERNAL_LINK',
    actionText: '投稿完了を申告',
    externalLink: 'https://finx.example.com/channels/introduction',
  },
  {
    id: 'daily-declaration',
    title: '今日のやること宣言',
    description: '「やること宣言部屋」に投稿したと見做して申告。毎日リセットされ、連続日数が記録されます。',
    icon: CalendarIcon,
    metric: 'dailyDeclarationCount',
    actionType: 'SELF_REPORT',
    actionText: '宣言する',
  },
  {
    id: 'testimonial',
    title: '応援メッセージを投稿',
    description: 'もくよう会への応援メッセージを書きましょう。承認されると「木曜会とは」ページに掲載されます。',
    icon: ChatBubbleIcon,
    metric: 'notesCount', // Not a direct metric, using a placeholder
    actionType: 'MODAL_FORM',
    actionText: 'メッセージを書く',
    payload: { form: 'testimonial' }
  },
  {
    id: 'notes',
    title: 'ノートを書く',
    description: '学習したことや成果をノートにまとめましょう。タイトルとURLを登録してください。',
    icon: BookOpenIcon,
    metric: 'notesCount',
    goal: 20,
    actionType: 'MODAL_FORM',
    actionText: 'ノートを登録',
    payload: { form: 'note' }
  },
  {
    id: 'offsite-meeting',
    title: 'オフ会に参加',
    description: 'オフラインでの交流も大切に。参加したら自己申告で回数を記録しましょう。',
    icon: UsersIcon,
    metric: 'offsiteCount',
    goal: 20,
    actionType: 'SELF_REPORT',
    actionText: '参加回数を+1',
  },
  {
    id: 'lt-win',
    title: 'LT会で優勝',
    description: 'ライトニングトーク会での優勝経験を記録します。自己申告後、管理者が承認します。',
    icon: TrophyIcon,
    metric: 'ltWinCount',
    goal: 2,
    actionType: 'SELF_REPORT',
    actionText: '優勝回数を+1',
  },
  {
    id: 'finx-posts',
    title: 'FINXの投稿数',
    description: 'FINXでの活動への貢献度です。この数値は管理者によって付与・更新されます。',
    icon: ClipboardListIcon,
    metric: 'finxPostsCount',
    actionType: 'VIEW_ONLY',
    actionText: '閲覧のみ',
  },
  {
    id: 'invites',
    title: 'もくよう会への招待',
    description: 'あなたの招待リンクから仲間を増やしましょう。自己申告も可能です。',
    icon: UserAddIcon,
    metric: 'invitesCount',
    actionType: 'INVITE',
    actionText: '招待リンクをコピー',
  },
];
